### ISSUE TITLE
Finally!

### ISSUE THREAD

**Issue by enoversum** [AminSallah/Flow.Launcher.Plugin.Notion#1]
This is not a bug report, as I haven't found any. But rather a sigh of relief—thank you so much for creating this plugin. 
Given that there _was_ a Notion plugin previously that was slow and ultimately given up upon a long time ago, I had almost buried my hope for a Notion integration for FlowLauncher. Your solution does not only work, but is elegant (think icons, which help with my code snippets database to differentiate what a snippet is meant for) and extremely fast. So thank you so much, this makes my life so much easier!

**Comment by AminSallah** [comment]
> This is not a bug report, as I haven't found any. But rather a sigh of relief—thank you so much for creating this plugin. Given that there _was_ a Notion plugin previously that was slow and ultimately given up upon a long time ago, I had almost buried my hope for a Notion integration for FlowLauncher. Your solution does not only work, but is elegant (think icons, which help with my code snippets database to differentiate what a snippet is meant for) and extremely fast. So thank you so much, this makes my life so much easier!

Thank you @enoversum for your thoughtful and encouraging words! It's great to hear that this plugin has positively impacted your workflow. Actually creating this plugin was a means for me to procrastinate from studying my lectures and I regretted spending time on it until I received your feedback. I'm glad it helped you out.

**Comment by enoversum** [comment]
> Thank you @enoversum for your thoughtful and encouraging words! It's great to hear that this plugin has positively impacted your workflow. Actually creating this plugin was a means for me to procrastinate from studying my lectures and I regretted spending time on it until I received your feedback. I'm glad it helped you out.

Well, in this case, you procrastinating helped doing a good deed to us. I'm pretty sure all the others that had reported they're missing a Notion integration are now happy as a heap of puppies as well. I'm using Notion all the time in my workday, so it's going to be an everyday helper. Cached results in FlowLauncher really make a big difference in terms of speed. No more each time opening the database URL, waiting for it to load, clicking into the search bar, typing and then waiting for the result.

Just a tiny thing for me, it took me a while until I understood what the relation setting means, maybe you could add a sentence or two to your 'documentation', as it were, to explain it.

**Comment by AminSallah** [comment]
I'm glad it's speeding up your process with Notion. I'll definitely consider adding more clarification about settings in the documentation to make it easier for users to understand . I also plan to embed every single detail; it's just a matter of time.

Thank you for taking the time to share your experience and suggestions! If you have any more thoughts or ideas, feel free to let me know.

**Comment by enoversum** [comment]
Thanks, @AminSallah , also for _your_ kind words. 

As for suggestions, well, for me personally, it would be cool if I could not only create a new page through your plugin and only get the notification for the page being created. It would be helpful if a) your plugin opened the new page's URL automatically after creating a specific note, so you can edit instead of only create it. 
Would also be cool if b) your plugin had some kind of shortcut for creating an empty new page and opened it in a database/page of choice, something like `c nn` to quickly create a new empty page. Best even if there were separate settings for default search and new-page databases in your plugin. 
I understand the shortcut-to-new-empty-note request would require some syntax for the command that avoids blocking the ability to search for parts of the command (in this case, you wouldn't be able to find a note with 'nn' in it). 

Edit: Also, being able to use multiple workspaces (I use two for different purposes) would be crazy cool. I'd love to define a main workspace where every search and other command is being executed by default, and an option to switch to a different one, so I can access data there.

**Comment by AminSallah** [comment]
Actually plugin already implemnt all of these except dealing with multiple workspaces but some of them still beta.

These tips to how you can create an emtpy page

1. Trigger the plugin using the action keyword `c` and choose a database using the action keyword for now is `@`, then press Enter to create.
2. To open anything in the browser or desktop app even after deletion, Hold the `CTRL` button and press Enter

https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/assets/124622454/5b7651e9-324a-4ba9-b44a-a0798e4cca4d


Many more features will be explained in the documentation upon completion.

**Comment by AminSallah** [comment]
> separate settings for default search and new-page databases in your plugin

I haven't implemented this because because Flow already provides this functionality. you can set custom query shortcuts in flow settings like this 

![Flow Launcher_jHYkHlw4n2](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/assets/124622454/8b16a666-35f7-4041-9948-5506b204901f)

If you want to remove a database from the search, you can easily hide all its pages by filtering the search to it. Simply set the name of the database between two dollar signs, like this:
`c $plugin demo$`, then press Shift + Enter, and select Hide all current query.

**Comment by enoversum** [comment]
Hey  @AminSallah , sorry for taking so long today :) . 
Thanks for pointing out that I can already open up pages I create in Notion/my browser by using Ctrl. However, since most of my new-page creations I also want to use, could you maybe provide a setting for the default behaviour? Using Ctrl, while this would be my standard procedure (create page, open it, because I want to use it), is just another step I need to remember, and also would defeat having a 'Custom Query Shortcut' (thanks for pointing that out!) if I still need to use the Ctrl key afterwards to actually open the note. So being able to toggle this behaviour (use Ctrl to just create, but not open the new page) would be awesome :) . 

Also, would you consider a default search vs. a default page-creation setting for your plugin? It's not urgent, just thought this might make it even a bit more comfortable.

**Comment by AminSallah** [comment]
Actually, it doesn't make sense to me about the quick capture plugin that by default forces you each time to open Notion. You know, just hit the Notion app and create it. But if this makes a big difference for you it's easy to do. Just fork the repository and look for this line in [Main.cs](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/blob/main/src/Main.cs). Add `!` before "c.SpecialKeyState" on the argument "open" to reverse it then build it.

Original:
```csharp
_ = subProcess(create: true, dict_arg: filtered_query, open: c.SpecialKeyState.CtrlPressed);
```

Edited:
```csharp
_ = subProcess(create: true, dict_arg: filtered_query, open: !c.SpecialKeyState.CtrlPressed);
```
Talking about your idea about default panel is search vs. page creation is interesting as well. Although it may not be an top priority, I'll keep it in mind for future updates. However, I cannot guarantee its addition at this time.

**Comment by AminSallah** [comment]
Closing this for now, feel free to reopen if further discussion is required

**Comment by enoversum** [comment]
> Actually, it doesn't make sense to me about the quick capture plugin that by default forces you each time to open Notion. You know, just hit the Notion app and create it. But if this makes a big difference for you it's easy to do. Just fork the repository and look for this line in [Main.cs](https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/blob/main/src/Main.cs). Add `!` before "c.SpecialKeyState" on the argument "open" to reverse it then build it.
> 
> Original:
> 
> ```cs
> _ = subProcess(create: true, dict_arg: filtered_query, open: c.SpecialKeyState.CtrlPressed);
> ```
> 
> Edited:
> 
> ```cs
> _ = subProcess(create: true, dict_arg: filtered_query, open: !c.SpecialKeyState.CtrlPressed);
> ```
> 
> Talking about your idea about default panel is search vs. page creation is interesting as well. Although it may not be an top priority, I'll keep it in mind for future updates. However, I cannot guarantee its addition at this time.

Sorry for taking so long, I currently have offline work in the real world that barely have me on my phone or computer :) . 
Thanks for your tip. For me, it makes a lot of sense to automatically open up new pages in Notion or my browser; I wouldn't create more than a title for a page through your extension before I open it up and fully compose it from there. In the unlikely case that I want to create a quick note with content without actually opening it, I could imagine circumventing the open-by-default behaviour by using my Ctrl key. 
I'm just saying this to stress that I might just have different needs than you, and I understand that it doesn't make sense to you. An option to reverse the behaviour thus would make sense for those with different workflows, at least I think so :) . 

On any account, I'm still very, very, very thankful for you having created this extension. The search is the most important thing for me that I had been craving for so long, and creating new pages via command-line is a very big bonus, so I didn't want to put any pressure on you to bring in any features that I would want, or want differently. So alas, thank you also for this conversation :) !

**Comment by AminSallah** [comment]
Thanks @enoversum for you feadback. Currently, there is a concept of adding a new list view in the settings panel to allow users to edit keywords and shortcuts scheduled for later. This is why adding it now may not be better, but I am currently working on v2. I plan to implement a brief logic for this by using the shift key. It's already done and working fine, so please hold on for version 2.

**Comment by enoversum** [comment]
Hey @AminSallah, all good, as I said, I was just suggesting something while I'm already very happy with your plugin. Take your time, but good to hear you already more or less implemented it ♥!

**Comment by enoversum** [comment]
Just go to come back, I've chatted with others, and apparently I'm not the only one wishing to create a page and then open it by default through your extension. So, if you would reconsider implementing a toggle optional for the Ctrl key behaviour/default when creating a page in your plugin, it appears it would not only make me even happier ☺!

**Comment by AminSallah** [comment]
It has already been implemented for some time, and currently testing v2 before releasing it.

**Comment by enoversum** [comment]
Ah, alright, I didn't understand it fully the first time around. Really happy to hear ♥!

**Comment by AminSallah** [comment]
Hello there, I just wanted to inform you that version 2 is now available. If the update doesn't appear in the plugins store, you can get it by pasting the following command into your Flow Launcher query bar:

`pm install https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/releases/download/v2.0.0/Flow.Launcher.Plugin.Notion.zip`

**Comment by enoversum** [comment]
> Hello there, I just wanted to inform you that version 2 is now available. If the update doesn't appear in the plugins store, you can get it by pasting the following command into your Flow Launcher query bar:
> 
> `pm install https://github.com/AminSallah/Flow.Launcher.Plugin.Notion/releases/download/v2.0.0/Flow.Launcher.Plugin.Notion.zip`

Hey Amin, gotcha! Needed to manually update it, but well, it's working now. So even better with the new option to open newly created pages directly. Thank you so much, that's beautiful!
