### ISSUE TITLE
Quick create Task

### ISSUE THREAD

**Issue by Ninu-Nightwatch** [AminSallah/Flow.Launcher.Plugin.Notion#14]
Hi Ami Sallah,

sorry to misuse the Issues tracker for a Question/Help:

I am looking to create a quick capture shortcut and would like to understand, if this is possible, with your Plugin. Like from Flow launcher I would like to hit the assigned letter and whatever I type after should be sent to notion and create a new entry in a Tasklist. 

Is this possible with your Plugin? If at all possible and you would help me to set it up, I would happily buy you a coffe on your support page.

Kind Regards!

**Comment by AminSallah** [comment]
Hi @SayeedAmitabTimo,

No worries about using the Issues tracker for questions! Yes, it is possible to create a quick capture shortcut, but it depends on your setup and workflow.

### Use a **database** as a Task List

One of the key features of this plugin is to quickly capture an idea that can be represented as a task or a database item. First, choose a default database from the settings panel. After that, type the plugin keyword `c`, then type the task name and press enter to create it. A new page will be created into seleced database with the same name entered in flow launcher

### Use a **page** as a Task List
If your workflow does not depend on a database to save tasks but only a `Todo block` on a Notion page, you can still quickly capture the task:

1. Type `c + "page name where you want to assign tasks"`
2. Press the `Tab` key on the desired page
3. Keep the auto-filled query as it is, then add the `*` symbol after it, followed by `Todo` to filter the results to the TodoList block
4. Copy the full query you have in the bar
5. Create a new query shortcut, whether it's a hotkey or just a shortcut
Now, when you want to quickly assign a new task list entry on a page, press the shortcut and then enter then write the task name.
Note: task would be assign after the last block of on the page

Here is an example:
![Flow](https://github.com/user-attachments/assets/2a6c1c84-42e6-43ea-9dc1-abf009660901)


Thanks for the coffee offer—much appreciated!

Kind regards,

**Comment by Ninu-Nightwatch** [comment]
Thank you, that was so easy now! 

I did try to buy you a coffee at https://ko-fi.com/amin_salah twice, but it's giving me an error. Let me know if you have other way.

![image](https://github.com/user-attachments/assets/b47916fe-dea3-47e9-8893-1c637ac6c518)

**Comment by AminSallah** [comment]
I'm glad I could help! Thanks for trying to buy me a coffee; I appreciate that. It looks like there might be an issue with the Ko-fi servers. If you'd like, you can use my PayPal me instead: https://paypal.me/aminsallah or using my paypal email address (medo.salah128@yahoo.com)
Thank you again!

**Comment by AminSallah** [comment]
Closing this for now. Feel free to reopen if further discussion is required.
