### ISSUE TITLE
"Create new page" has a way too high score in the results list

### ISSUE THREAD

**Issue by Chaoscontrol** [AminSallah/Flow.Launcher.Plugin.Notion#17]
I like to use the plugin without a specific keyword, so it finds existing Notion pages easily. 

However, I've been bothered constantly by the "Create ... page" result popping up FIRST in the results list, even above other results that were way more fitting from other plugins. 

I even went to the extent of setting lower priority to the plugin. And not even then it worked. The "Create new page" seems to have a perfect score every single time. 

![image](https://github.com/user-attachments/assets/39c98d0b-e0b7-419b-b303-d37f9cd1a417)

No it doesn't have "Set as top most result". I made sure of that. 

After asking for help on Discord, they mentioned for me to try and set priority -100. Once I did, it did work and the result doesn't show up above everything anymore. 

But still, I think this particular result score should be reviewed. Especially since it's a result to create something that doesn't exist. So it should always be the last resort when nothing else is matching.

**Comment by AminSallah** [comment]
Hey @Chaoscontrol, 

The "Create" option had top priority in an old beta version, but I found a better way to handle it and forgot about setting the "Create" priority back—thanks for bringing this to my attention. 

In v5, this issue should be fixed, and "Create" will no longer appear at the top.
